CREATE TABLE "redemption_requests" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"merchant_user_id" bigint NOT NULL,
	"merchant_wallet" text NOT NULL,
	"merchant_account" text NOT NULL,
	"merchant_ata" text NOT NULL,
	"redemption_request" text NOT NULL,
	"redemption_id" text NOT NULL,
	"amount" text NOT NULL,
	"amount_usd" text NOT NULL,
	"currency" text NOT NULL,
	"decimals" text NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"request_tx" text NOT NULL,
	"approve_tx" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "redemption_requests_redemption_request_unique" UNIQUE("redemption_request"),
	CONSTRAINT "redemption_requests_merchant_redemption_id_unique" UNIQUE("merchant_wallet","redemption_id")
);
