[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
travel_ramp = "8auatzShQgGGu6HbNhfPmxFZKNQUzrzW7j7X2n8Knp5g"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
